name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual deployment'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show manual run reason
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual deployment reason ${{ github.event.inputs.reason }}"
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: |
            apps/frontend/package-lock.json
            apps/api-server/package-lock.json
            apps/mcp-server/package-lock.json

      - name: Make tg command executable
        run: chmod +x cli/taskgraph-editor.sh bin/tg

      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 3
          npm config set fetch-retry-mintimeout 10000
          npm config set fetch-retry-maxtimeout 60000

      - name: Run linter
        run: ./bin/tg lint
        timeout-minutes: 5

      - name: Build for GitHub Pages
        run: |
          cd apps/frontend
          VITE_GITHUB_PAGES=true VITE_READONLY_MODE=true npm run build
        timeout-minutes: 5

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4