name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: Make tg command executable
      run: chmod +x cli/taskgraph-editor.sh bin/tg

    - name: Run linter
      run: ./bin/tg lint
      timeout-minutes: 5

    - name: Start API server
      run: |
        cd apps/api-server
        npm install
        nohup npm start &
        sleep 5
        curl --retry 5 --retry-delay 2 --connect-timeout 5 http://localhost:3333 || exit 1

    - name: Run frontend tests
      run: ./bin/tg test-frontend
      timeout-minutes: 5

    - name: Run API tests
      run: ./bin/tg test-api
      timeout-minutes: 5