name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - name: Show manual run reason
      if: github.event_name == 'workflow_dispatch'
      run: echo "Manual run reason ${{ github.event.inputs.reason }}"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: |
          apps/frontend/package-lock.json
          apps/api-server/package-lock.json
          apps/mcp-server/package-lock.json

    - name: Make tg command executable
      run: chmod +x cli/taskgraph-editor.sh bin/tg

    - name: Configure npm
      run: |
        npm config set registry https://registry.npmjs.org/
        npm config set fetch-retries 3
        npm config set fetch-retry-mintimeout 10000
        npm config set fetch-retry-maxtimeout 60000

    - name: Run linter
      run: ./bin/tg lint
      timeout-minutes: 5
      continue-on-error: false

    - name: Run frontend tests
      run: ./bin/tg test-frontend
      timeout-minutes: 5
      continue-on-error: false

    - name: Run API tests
      run: ./bin/tg test-api
      timeout-minutes: 5
      continue-on-error: false

    - name: Test build (MCP server and API Client)
      run: ./bin/tg build
      timeout-minutes: 5
      continue-on-error: false

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ci-logs
        path: |
          apps/frontend/node_modules/.cache/
          apps/api-server/node_modules/.cache/
          apps/mcp-server/node_modules/.cache/
        retention-days: 7
